---
wireguard_windows_staging_dir: C:\ProgramData\ansible-common\wireguard-staging
wireguard_windows_hub_private_key: "{{ resolved_wireguard_network.hub_member.private_key | default('CHANGE_ME_WIREGUARD_HUB_PRIVATE_KEY') }}"
wireguard_windows_hub_public_key: "{{ resolved_wireguard_network.hub_public_key | default('CHANGE_ME_WIREGUARD_HUB_PUBLIC_KEY') }}"
