---
- name: Check WireGuard members
  hosts: "{{ target_group | mandatory }}"
  gather_facts: false

  pre_tasks:
    - name: Load architecture model
      ansible.builtin.include_role:
        name: ansible_common.core.model_load

    - name: Normalize architecture model
      ansible.builtin.include_role:
        name: ansible_common.core.model_normalize

  roles:
    - role: ansible_common.core.wireguard_healthcheck
