---
- name: Apply XP2P members one at a time
  hosts: "{{ target_group | mandatory }}"
  gather_facts: false
  serial: 1

  pre_tasks:
    - name: Load architecture model
      ansible.builtin.include_role:
        name: ansible_common.core.model_load

    - name: Normalize architecture model
      ansible.builtin.include_role:
        name: ansible_common.core.model_normalize

    - name: Skip hosts that are not members of the selected XP2P network
      ansible.builtin.meta: end_host
      when: resolved_xp2p_network.current_member | default(None) is none

  roles:
    - role: ansible_common.core.xp2p_apply
