---
- name: Apply XP2P server redirects
  ansible.builtin.import_playbook: xp2p_server_redirects_apply.yml
  vars:
    target_group: "{{ xp2p_server_target_group | mandatory }}"

- name: Apply XP2P client redirects
  ansible.builtin.import_playbook: xp2p_client_apply.yml
  vars:
    target_group: "{{ xp2p_client_target_group | mandatory }}"
